/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sopes2_problema1_filosofos;

import java.util.concurrent.locks.ReentrantLock;

/**
 *
 * @author Saul Guzman ◢◤
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panelprincipal = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        logarea = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        fil1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        fil3 = new javax.swing.JLabel();
        fil2 = new javax.swing.JLabel();
        fil4 = new javax.swing.JLabel();
        fil5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        textsleep = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        plat1 = new javax.swing.JLabel();
        plat5 = new javax.swing.JLabel();
        plat4 = new javax.swing.JLabel();
        plat3 = new javax.swing.JLabel();
        plat2 = new javax.swing.JLabel();
        ten1 = new javax.swing.JLabel();
        ten2 = new javax.swing.JLabel();
        ten5 = new javax.swing.JLabel();
        ten3 = new javax.swing.JLabel();
        ten4 = new javax.swing.JLabel();
        bt5 = new javax.swing.JButton();
        bt4 = new javax.swing.JButton();
        bt3 = new javax.swing.JButton();
        bt1 = new javax.swing.JButton();
        bt2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        logarea.setEditable(false);
        logarea.setColumns(20);
        logarea.setRows(5);
        jScrollPane1.setViewportView(logarea);

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel2.setText("SOPES2-G4 - PROBLEMA 1");

        jButton1.setText("INICIAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        fil1.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        fil1.setForeground(new java.awt.Color(255, 0, 0));
        fil1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sopes2_problema1_filosofos/filo.jpg"))); // NOI18N
        fil1.setText("1");

        jLabel1.setText("Log del Programa:");

        fil3.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        fil3.setForeground(new java.awt.Color(255, 0, 0));
        fil3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sopes2_problema1_filosofos/filo.jpg"))); // NOI18N
        fil3.setText("3");

        fil2.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        fil2.setForeground(new java.awt.Color(255, 0, 0));
        fil2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sopes2_problema1_filosofos/filo.jpg"))); // NOI18N
        fil2.setText("2");

        fil4.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        fil4.setForeground(new java.awt.Color(255, 0, 0));
        fil4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sopes2_problema1_filosofos/filo.jpg"))); // NOI18N
        fil4.setText("4");

        fil5.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        fil5.setForeground(new java.awt.Color(255, 0, 0));
        fil5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sopes2_problema1_filosofos/filo.jpg"))); // NOI18N
        fil5.setText("5");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel4.setText("FILOSOFOS PENSANTES");

        jLabel5.setText("Tiempo Sleep (Ej: 10000)");

        plat1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sopes2_problema1_filosofos/plato.jpg"))); // NOI18N

        plat5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sopes2_problema1_filosofos/plato.jpg"))); // NOI18N

        plat4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sopes2_problema1_filosofos/plato.jpg"))); // NOI18N

        plat3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sopes2_problema1_filosofos/plato.jpg"))); // NOI18N

        plat2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sopes2_problema1_filosofos/plato.jpg"))); // NOI18N

        ten1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sopes2_problema1_filosofos/895215.png"))); // NOI18N
        ten1.setText("1");

        ten2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sopes2_problema1_filosofos/895215.png"))); // NOI18N
        ten2.setText("2");

        ten5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sopes2_problema1_filosofos/895215.png"))); // NOI18N
        ten5.setText("5");

        ten3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sopes2_problema1_filosofos/895215.png"))); // NOI18N
        ten3.setText("3");

        ten4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sopes2_problema1_filosofos/895215.png"))); // NOI18N
        ten4.setText("4");

        bt5.setBackground(new java.awt.Color(153, 255, 153));
        bt5.setText("Pensar");

        bt4.setBackground(new java.awt.Color(153, 255, 153));
        bt4.setText("Pensar");

        bt3.setBackground(new java.awt.Color(153, 255, 153));
        bt3.setText("Pensar");

        bt1.setBackground(new java.awt.Color(153, 255, 153));
        bt1.setText("Pensar");

        bt2.setBackground(new java.awt.Color(153, 255, 153));
        bt2.setText("Pensar");

        javax.swing.GroupLayout PanelprincipalLayout = new javax.swing.GroupLayout(Panelprincipal);
        Panelprincipal.setLayout(PanelprincipalLayout);
        PanelprincipalLayout.setHorizontalGroup(
            PanelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelprincipalLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(PanelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelprincipalLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(PanelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelprincipalLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PanelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ten4)
                                    .addGroup(PanelprincipalLayout.createSequentialGroup()
                                        .addGroup(PanelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(PanelprincipalLayout.createSequentialGroup()
                                                .addComponent(fil5)
                                                .addGap(29, 29, 29)
                                                .addGroup(PanelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(plat5)
                                                    .addComponent(ten1))
                                                .addGap(25, 25, 25))
                                            .addGroup(PanelprincipalLayout.createSequentialGroup()
                                                .addComponent(bt5)
                                                .addGap(148, 148, 148)))
                                        .addGroup(PanelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(fil1)
                                            .addGroup(PanelprincipalLayout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(plat1))))
                                    .addComponent(bt1))
                                .addGroup(PanelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelprincipalLayout.createSequentialGroup()
                                        .addGap(38, 38, 38)
                                        .addGroup(PanelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(PanelprincipalLayout.createSequentialGroup()
                                                .addComponent(plat2)
                                                .addGap(27, 27, 27)
                                                .addComponent(fil2)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addGroup(PanelprincipalLayout.createSequentialGroup()
                                                .addComponent(ten2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(bt2))))
                                    .addGroup(PanelprincipalLayout.createSequentialGroup()
                                        .addGap(75, 75, 75)
                                        .addComponent(fil3)
                                        .addContainerGap())))
                            .addGroup(PanelprincipalLayout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addGroup(PanelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ten5)
                                    .addGroup(PanelprincipalLayout.createSequentialGroup()
                                        .addComponent(bt4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(fil4)))
                                .addGroup(PanelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelprincipalLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(plat4)
                                        .addGap(49, 49, 49)
                                        .addComponent(plat3)
                                        .addGap(18, 18, 18)
                                        .addComponent(ten3)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelprincipalLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(bt3)
                                        .addGap(26, 26, 26))))))
                    .addGroup(PanelprincipalLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap())))
            .addGroup(PanelprincipalLayout.createSequentialGroup()
                .addGroup(PanelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelprincipalLayout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jLabel2)
                        .addGap(83, 83, 83)
                        .addComponent(jLabel4))
                    .addGroup(PanelprincipalLayout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(jLabel5)
                        .addGap(38, 38, 38)
                        .addComponent(textsleep, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelprincipalLayout.setVerticalGroup(
            PanelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelprincipalLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(PanelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(PanelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(textsleep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(PanelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(bt1))
                .addGap(18, 18, 18)
                .addGroup(PanelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(PanelprincipalLayout.createSequentialGroup()
                            .addGroup(PanelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(PanelprincipalLayout.createSequentialGroup()
                                    .addGroup(PanelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(PanelprincipalLayout.createSequentialGroup()
                                            .addGap(46, 46, 46)
                                            .addGroup(PanelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(ten2)
                                                .addComponent(ten1)))
                                        .addGroup(PanelprincipalLayout.createSequentialGroup()
                                            .addGap(62, 62, 62)
                                            .addComponent(plat1)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelprincipalLayout.createSequentialGroup()
                                    .addComponent(bt2)
                                    .addGap(18, 18, 18)))
                            .addGroup(PanelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(plat4)
                                .addGroup(PanelprincipalLayout.createSequentialGroup()
                                    .addComponent(fil2)
                                    .addGap(45, 45, 45)
                                    .addComponent(plat3)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fil3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(bt3)
                            .addContainerGap(22, Short.MAX_VALUE))
                        .addGroup(PanelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bt4)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PanelprincipalLayout.createSequentialGroup()
                        .addComponent(fil1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addComponent(bt5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelprincipalLayout.createSequentialGroup()
                                .addGroup(PanelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelprincipalLayout.createSequentialGroup()
                                        .addGroup(PanelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(plat5)
                                            .addComponent(fil5))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelprincipalLayout.createSequentialGroup()
                                        .addComponent(plat2)
                                        .addGap(23, 23, 23)))
                                .addGroup(PanelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ten3)
                                    .addComponent(ten5))
                                .addGap(48, 48, 48)
                                .addComponent(fil4)
                                .addContainerGap(56, Short.MAX_VALUE))
                            .addGroup(PanelprincipalLayout.createSequentialGroup()
                                .addGap(171, 171, 171)
                                .addComponent(ten4)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addComponent(Panelprincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Panelprincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Ventana vent = this;
        int nums = Integer.parseInt(this.textsleep.getText());
        Mesa mesafilosofos = new Mesa();
        for(int i=0; i<5; i++){
            Filosofo filosofo = new Filosofo(nums,vent,i, mesafilosofos);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    void Imprimir(String cadena){
        ReentrantLock lock = new ReentrantLock();
        lock.lock();
        logarea.append(cadena);
        lock.unlock();
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel Panelprincipal;
    public javax.swing.JButton bt1;
    public javax.swing.JButton bt2;
    public javax.swing.JButton bt3;
    public javax.swing.JButton bt4;
    public javax.swing.JButton bt5;
    private javax.swing.JLabel fil1;
    private javax.swing.JLabel fil2;
    private javax.swing.JLabel fil3;
    private javax.swing.JLabel fil4;
    private javax.swing.JLabel fil5;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextArea logarea;
    public javax.swing.JLabel plat1;
    public javax.swing.JLabel plat2;
    public javax.swing.JLabel plat3;
    public javax.swing.JLabel plat4;
    public javax.swing.JLabel plat5;
    public javax.swing.JLabel ten1;
    public javax.swing.JLabel ten2;
    public javax.swing.JLabel ten3;
    public javax.swing.JLabel ten4;
    public javax.swing.JLabel ten5;
    private javax.swing.JTextField textsleep;
    // End of variables declaration//GEN-END:variables
}
